### ISSUE TITLE
Finish the --get-all function

### ISSUE THREAD

**Issue by rwils83** [rwils83/nvd_api_interactions#2]
I just haven't had time to write this function. Basically it needs to get all the things from the NVD

**Comment by Foo-Maker** [comment]
Hey.

I'm not a pro but i think i could take this challenge into a goal. 

Lets have a look for the PR #6 

And can you please add the hacktoberfest-accepted label to the PR or the hacktoberfest label to the repo?
At the moment i have an "Project not participating" 

Thank you
