### ISSUE TITLE
Write the read me file

### ISSUE THREAD

**Issue by rwils83** [rwils83/nvd_api_interactions#3]
This thing needs a readme.md file. I have a standard template I use, located at https://github.com/rwils83/standard_docs_for_me. I normally would not open this up, but I want as many people to have a chance with Hacktoberfest as possible.

**Comment by HammedBabatunde** [comment]
Can you assign this to me @rwils83

**Comment by rwils83** [comment]
Sure @HammedBabatunde done. Thanks for offering!
