### ISSUE TITLE
Write Unittests for this thing     

### ISSUE THREAD

**Issue by rwils83** [rwils83/nvd_api_interactions#4]
Coding should have testing, but I don't like writing testing because I am not good at it. Opening up for Hacktoberfest

**Comment by shepherdjay** [comment]
Hi @rwils83 - I love testing and teaching testing - I can give you a hand if you would like

**Comment by rwils83** [comment]
@shepherdjay Definitely! Thank you for the PR and I am always up for learning new things!!!
